name: Deploy to GitHub Pages

on:
  # Se ejecuta cada vez que haces push a la rama principal
  push:
    branches: ["main"]
  # Permite ejecutar este flujo de trabajo manualmente desde la pestaña Actions
  workflow_dispatch:

# Permisos necesarios para que GitHub Actions pueda publicar en Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite solo una ejecución concurrente de despliegue, omitiendo las ejecuciones en cola
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Ruta donde Vite genera los archivos compilados
          path: "./docs"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
